on: [push]
name: Deploy_My_FastAPI_App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure using the service principal credentials
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build the Docker image and push it to ACR
      - name: Build and push image
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-fastapi-app:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-fastapi-app:${{ github.sha }}

      # Deploy the container image to Azure Container Instances
      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: my-fastapi-app-${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-fastapi-app:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: my-fastapi-app
          location: centralindia
